name: Normalize GitBook assets for Git it Write

on:
  push:
    branches: [ main ]          # change if your default branch differs
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: normalize-assets-${{ github.ref }}
  cancel-in-progress: true

jobs:
  normalize:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update to latest main (rebase)
        run: |
          git fetch origin main
          git checkout main
          git rebase origin/main

      - name: Ensure _images exists
        run: mkdir -p _images/gitbook

      - name: Copy from .gitbook/assets
        run: |
          if [ -d ".gitbook/assets" ]; then
            rsync -a --delete ".gitbook/assets/" "_images/gitbook/"
          fi

      - name: Rewrite /main/.gitbook/assets → /main/_images/gitbook in Markdown
        shell: bash
        run: |
          set -e
          shopt -s nullglob
          # Rewrite in md / mdx / markdown (upper/lower-case variants too)
          git grep -l '/main/.gitbook/assets/' -- \
            '**/*.md' '**/*.MD' '**/*.mdx' '**/*.MDX' '**/*.markdown' '**/*.MARKDOWN' \
          | xargs -r sed -i 's#/main/\.gitbook/assets/#/main/_images/gitbook/#g'

          # OPTIONAL: fail if anything still points to .gitbook/assets
          if git grep -n '\.gitbook/assets' -- '**/*.md' '**/*.MD' '**/*.mdx' '**/*.MDX' '**/*.markdown' '**/*.MARKDOWN'; then
            echo "Found remaining .gitbook/assets references." >&2
            # exit 1   # uncomment to force failure until all are fixed
          fi

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Normalize: /main/.gitbook/assets → /main/_images/gitbook [ci skip]"
          else
            echo "No changes to co
