name: Normalize GitBook assets for Git it Write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: normalize-assets-${{ github.ref }}
  cancel-in-progress: true

jobs:
  normalize:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Configure author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update to latest main (rebase)
        run: |
          git fetch origin main
          git checkout main
          git rebase origin/main

      - name: Ensure _images exists (flat)
        run: mkdir -p _images

      # 1) Copy images from .gitbook/assets → _images (flat)
      - name: Copy from .gitbook/assets → _images (flat)
        shell: bash
        run: |
          set -euo pipefail
          if [ -d ".gitbook/assets" ]; then
            while IFS= read -r -d '' src; do
              base="$(basename "$src")"
              cp -f "$src" "_images/$base"
            done < <(find .gitbook/assets -type f -print0)
          fi

      # 2) Rename files in _images to remove spaces (spaces -> '-')
      - name: Slugify filenames in _images (remove spaces)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          for f in _images/*; do
            b="$(basename "$f")"
            nb="$(printf '%s' "$b" | sed -E 's/%20/ /g; s/[[:space:]]+/-/g; s/-+/-/g')"
            if [ "$b" != "$nb" ]; then
              tgt="_images/$nb"
              if [ -e "$tgt" ]; then
                # If target exists and content is IDENTICAL → drop the duplicate
                if cmp -s "$f" "$tgt"; then
                  git rm -f "$f" 2>/dev/null || rm -f "$f"
                  echo "Removed duplicate identical file: $b (kept $(basename "$tgt"))"
                  continue
                fi
                # Else different content → create a unique name (rare)
                base="${nb%.*}"; ext="${nb##*.}"; i=1
                while [ -e "_images/${base}-${i}.${ext}" ]; do i=$((i+1)); done
                tgt="_images/${base}-${i}.${ext}"
              fi
              git mv -f "$f" "$tgt" 2>/dev/null || mv -f "$f" "$tgt"
              echo "Renamed: $b -> $(basename "$tgt")"
            fi
          done
      

      # 3) Convert <figure><img ...><figcaption>...</figcaption></figure> → ![alt](/_images/file "alt")
      - name: Convert <figure><img> blocks to Markdown images (/_images, no spaces)
        shell: bash
        run: |
          set -euo pipefail
          python3 - <<'PY'
          import re, glob, html, os

          def slug_filename(name:str)->str:
            import os, re
            name = name.replace('%20',' ')
            base, ext = os.path.splitext(name)

            # --- NEW fix: strip quoted fragment INSIDE trailing parentheses, keep ')'
            # e.g. image-(766 "Clicking \"…\"")  ->  image-(766)
            base = re.sub(r'\(\s*([^()"]*?)\s+"(?:[^"\\]|\\.)*"\s*\)$', r'(\1)', base)

            # If base ends with (...) (no quotes), still normalize its inner spacing
            m = re.search(r'\(([^()]*)\)$', base)
            if m:
              inner = m.group(1)
              inner = re.sub(r'\s+', ' ', inner).strip()
              base = base[:m.start()] + f'({inner})'

            # Fallback removals
            base = re.sub(r'\s+"(?:[^"\\]|\\.)*"\s*', '', base)  # space+"…"
            base = re.sub(r'["“”].*$', '', base)                 # anything after stray quote

            # Normalize whitespace/symbols
            base = re.sub(r'\s+', '-', base)
            base = re.sub(r'-{2,}', '-', base).strip('-')

            return f"{base}{ext.lower()}"

          files = [p for g in ["**/*.md","**/*.MD","**/*.mdx","**/*.MDX","**/*.markdown","**/*.MARKDOWN"]
                   for p in glob.glob(g, recursive=True)]

          FIG = re.compile(r'<figure\b[^>]*>(.*?)</figure>', re.I|re.S)
          IMG = re.compile(r'<img\b[^>]*>', re.I|re.S)
          CAP = re.compile(r'<figcaption\b[^>]*>(.*?)</figcaption>', re.I|re.S)
          def attr(n,s):
              m = re.search(rf'\b{n}\s*=\s*["\']([^"\']*)["\']', s, re.I|re.S)
              return m.group(1).strip() if m else ''

          def convert(block:str)->str:
              m = IMG.search(block)
              if not m: return block
              img = m.group(0)
              raw_src = attr('src', img)
              alt = attr('alt', img)

              mcap = CAP.search(block)
              cap = html.unescape(re.sub(r'<[^>]+>','',mcap.group(1))).strip() if mcap else ""
              title = cap or alt

              fn = slug_filename(os.path.basename(raw_src))
              url = f"/_images/{fn}"
              alt_md = (alt or '').replace(']', r'\]')
              title_md = (title or '').replace('"', r'\"')
              return f'![{alt_md}]({url} "{title_md}")' if title_md else f'![{alt_md}]({url})'

          for path in files:
              s = open(path, encoding="utf-8").read()
              n = FIG.sub(lambda m: convert(m.group(0)), s)
              if n != s:
                  open(path, "w", encoding="utf-8").write(n)
                  print(f"Converted figures in: {path}")
          PY
      
      
      
      

      # 4) Normalize any remaining image links to /_images/<no-spaces>, remove prefixes/subfolders, convert bare <img> too
      - name: Normalize ALL image links to ![alt](/_images/<slug> "alt") exactly
        shell: bash
        run: |
          set -euo pipefail
          python3 - <<'PY'
          import re, glob, os
          from urllib.parse import unquote
          from html import unescape

          IMG_EXT = r"(?:png|jpe?g|gif|webp|svg|gifv)"

          def clean_filename_from_url(url: str) -> str:
            import os, re
            from urllib.parse import unquote

            if not url:
              return "unknown.png"

            url = url.strip().rstrip('>')
            url = re.sub(r'\s*""', '', url)

            # last filename-like token
            m = re.findall(rf'([^/?#]+?\.{IMG_EXT})', url, flags=re.I)
            bn = m[-1] if m else os.path.basename(url)
            bn = unquote(bn)

            # split
            if "." in bn:
              base, ext = bn.rsplit(".", 1)
            else:
              base, ext = bn, ""

            # --- NEW fix: strip quoted fragment INSIDE trailing parentheses, keep ')'
            # e.g. image-(766 "Clicking \"…\"")  ->  image-(766)
            base = re.sub(r'\(\s*([^()"]*?)\s+"(?:[^"\\]|\\.)*"\s*\)$', r'(\1)', base)

            # If base ends with (...) (no quotes), still normalize its inner spacing
            pm = re.search(r'\(([^()]*)\)$', base)
            if pm:
              inner = pm.group(1)
              inner = re.sub(r'\s+', ' ', inner).strip()
              base = base[:pm.start()] + f'({inner})'

            # Fallback cleanups
            base = re.sub(r'\s+"(?:[^"\\]|\\.)*"\s*', '', base)  # space+"…"
            base = re.sub(r'["“”].*$', '', base)                 # cut from any stray quote

            # normalize: spaces -> dash; allow (), -, _
            base = re.sub(r"\s+", "-", base)
            base = re.sub(r"[^A-Za-z0-9_\-()]", "-", base)
            base = re.sub(r"-{2,}", "-", base).strip("-")

            return f"{base}.{ext.lower()}" if ext else base

          def to_root_image_url(url: str) -> str:
              return "/_images/" + clean_filename_from_url(url)

          def norm_text(s: str) -> str:
              t = unescape(s or "")
              t = t.replace("“", '"').replace("”", '"').replace("’", "'")
              return t

          def build_md(alt: str, url: str) -> str:
              alt = norm_text(alt or "")
              alt_md = alt.replace("]", r"\]")
              if alt.strip():
                  title = alt.replace('"', r'\"')
                  return f'![{alt_md}]({to_root_image_url(url)} "{title}")'
              else:
                  return f'![{alt_md}]({to_root_image_url(url)})'

          md_files = [p for g in ("**/*.md","**/*.MD","**/*.mdx","**/*.MDX","**/*.markdown","**/*.MARKDOWN")
                      for p in glob.glob(g, recursive=True)]

          HINT_BLOCK = re.compile(r'{%\s*hint\b[^%]*%}(.*?){%\s*endhint\s*%}', re.I | re.S)
          MD_LINK    = re.compile(r'\[([^\]]+)\]\((https?://[^)]+)\)')
          BARE_URL   = re.compile(r'^(https?://\S+)$')
          def convert_hint_blocks(s: str) -> str:
              def _repl(m):
                  inner = m.group(1).strip()
                  paras = []
                  for line in inner.splitlines():
                      line = line.strip()
                      if not line:
                          continue
                      line = MD_LINK.sub(r'<a href="\2">\1</a>', line)
                      bu = BARE_URL.match(line)
                      if bu:
                          u = bu.group(1)
                          line = f'<a href="{u}">{u}</a>'
                      paras.append(f"<p>{line}</p>")
                  content = "\n".join(paras) if paras else "<p></p>"
                  return f'<blockquote class="wp-block-quote">\n{content}\n</blockquote>'
              return HINT_BLOCK.sub(_repl, s)

          html_img = re.compile(
              r'<img\b[^>]*\bsrc=["\']([^"\']+)["\'][^>]*?(?:\balt=["\']([^"\']*)["\'])?[^>]*>',
              re.I
          )

          # Inline Markdown images (URL captured up to image extension; allows ')' inside filename)
          md_img_inline = re.compile(
          r'!\[([^\]]*)\]'          # alt
          r'\('
          r'\s*<?'
          r'("?)(.*?\.(?:png|jpe?g|gif|webp|svg|gifv)(?:\?[^\s")]+)?)\1'  # URL up to image ext
          r'>?'
          r'(?:\s+"[^"]*")?'        # optional title
          r'\s*\)',
          re.I | re.S
          )
          
          # Catch-all sanitizer with same URL rule
          md_img_any = re.compile(
          r'!\[([^\]]*)\]'
          r'\('
          r'\s*<?'
          r'(.*?\.(?:png|jpe?g|gif|webp|svg|gifv)(?:\?[^\s")]+)?)'        # URL up to image ext
          r'>?'
          r'(?:\s+"[^"]*")?'
          r'\s*\)',
          re.I | re.S
          )
  
  
          md_img_ref_use = re.compile(r'!\[([^\]]*)\]\s*\[([^\]]+)\]', re.I)
          ref_def_loose = re.compile(
              r'(\[([^\]]+)\]\s*:\s*)' r'<?("?)([^>\r\n]+?)\3>?' r'(\s+"[^"]*")?\s*$',
              re.I
          )

          any_changed = False
          for path in md_files:
              with open(path, encoding="utf-8") as f:
                  s = f.read()
              o = s

              s = html_img.sub(lambda m: build_md(m.group(2) or "", m.group(1)), s)
              s = md_img_inline.sub(lambda m: build_md(m.group(1), m.group(3)), s)
              s = convert_hint_blocks(s)

              def _sanitize_md_img(m):
                alt = m.group(1)
                inner = (m.group(2) or "").strip()
                if not inner:
                  return m.group(0)
                extm = re.search(rf'\.{IMG_EXT}\b', inner, re.I)
                if extm:
                  inner = inner[:extm.end()]
                # Escaped-aware removal of embedded titles
                inner = re.sub(r'\s+"(?:[^"\\]|\\.)*"\s*', '', inner)
                return build_md(alt, inner)
              s = md_img_any.sub(_sanitize_md_img, s)

              defs = {}
              lines = s.splitlines()
              for ln in lines:
                  m = ref_def_loose.search(ln)
                  if m:
                      rid = m.group(2).strip()
                      url = m.group(4).strip()
                      defs[rid] = url

              def repl_ref_use(m):
                  alt, rid = m.group(1), m.group(2).strip()
                  url = defs.get(rid)
                  return build_md(alt, url) if url else m.group(0)
              s = md_img_ref_use.sub(repl_ref_use, s)

              def rewrite_def_line(ln: str) -> str:
                  m = ref_def_loose.search(ln)
                  if not m:
                      return ln
                  head, url, title = m.group(1), m.group(4).strip(), m.group(5) or ""
                  new_url = to_root_image_url(url)
                  return f"{head}{new_url}{title}"
              s = "\n".join(rewrite_def_line(ln) for ln in s.splitlines())

              out_lines, fenced = [], False
              fence_re = re.compile(r'^\s*```')
              asset_re = re.compile(r'(\.gitbook/assets/[^"\'<>]+)', re.I)
              for ln in s.splitlines():
                  if fence_re.match(ln):
                      fenced = not fenced
                      out_lines.append(ln); continue
                  if not fenced and '.gitbook/assets/' in ln:
                      ln = asset_re.sub(lambda m: to_root_image_url(m.group(1)), ln)
                  out_lines.append(ln)
              s = "\n".join(out_lines)

              s = re.sub(r'\]\(\s*<?(?:\.\./|\.?/)+_images/', '](/_images/', s)
          
          # 4.9) Final defuser: if any space+"title" leaked into the filename just before the extension, strip it.
            # Example: /_images/image-(766 "Clicking ...").png  ->  /_images/image-(766).png
              s = re.sub(
              r'(/_images/[^\s)]+?)\s+"(?:[^"\\]|\\.)*"\s*(\.(?:png|jpe?g|gif|webp|svg|gifv))',
              r'\1\2',
              s,
              flags=re.I
              )


          if s != o:
                  with open(path, "w", encoding="utf-8") as f:
                      f.write(s)
                  print(f"Fixed: {path}")
                  any_changed = True

          if not any_changed:
              print("No image links needed normalization.")
          PY
      
      
      
      

      # 5) Validate: all image links are /_images/<no-spaces> and no subfolders
      - name: Validate image links style (/_images/*, no spaces)
        shell: bash
        run: |
          set -euo pipefail
          python3 - <<'PY'
          import re, glob, sys

          exts   = r"(png|jpe?g|gif|webp|svg|gifv)"
          is_img = re.compile(rf"\.({exts})(?:$|\?)", re.I)

          # Inline MD
          md_img_inline = re.compile(
            r'!\[([^\]]*)\]'           # alt text
            r'\('
            r'\s*<?'
            r'("?)([^)\r\n]+?)\1'      # group 3 = URL only
            r'>?'                      # optional >, not captured
            r'(?:\s+"[^"]*")?'
            r'\s*\)',
            re.I
          )
          # HTML
          html_src = re.compile(r'\bsrc=["\']([^"\']+)["\']', re.I)
          # Loose ref def (line-by-line)
          ref_def_loose = re.compile(
              r'(\[([^\]]+)\]\s*:\s*)' r'<?("?)([^>\r\n]+?)\3>?' r'(\s+"[^"]*")?\s*$',
              re.I
          )

          def bad(u: str) -> bool:
              u = u.strip()
              if u.startswith("http://") or u.startswith("https://"):
                  return False  # ignore external images
              if not is_img.search(u):
                  return False
              if not u.startswith("/_images/"):
                  return True
              rest = u[len("/_images/"):]
              if "/" in rest:
                  return True
              if " " in u:
                  return True
              return False

          bads = []
          files = [p for g in ("**/*.md","**/*.MD","**/*.mdx","**/*.MDX","**/*.markdown","**/*.MARKDOWN")
                   for p in glob.glob(g, recursive=True)]
          for p in files:
              with open(p, encoding="utf-8") as f:
                  s = f.read()

              # Inline MD
              for m in md_img_inline.finditer(s):
                  u = m.group(2).strip()
                  if bad(u): bads.append((p, u))

              # HTML
              for u in html_src.findall(s):
                  if bad(u): bads.append((p, u))

              # Ref defs
              for ln in s.splitlines():
                  m = ref_def_loose.search(ln)
                  if m:
                      u = m.group(4).strip()
                      if bad(u): bads.append((p, u))

          if bads:
              print("Non-compliant image links:")
              for p, u in bads:
                  print(f"- {p}: {u}")
              sys.exit(1)

          print("All local image links are /_images/<file> with no spaces and no subfolders. External URLs are ignored.")
          PY
      

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Normalize: convert figures and links to ![alt](/_images/file \"alt\"), no spaces [ci skip]"
          else
            echo "No changes to commit."
          fi

      - name: Rebase on latest and push (retry with --force-with-lease)
        shell: bash
        run: |
          set -euo pipefail
          git fetch origin main --prune
          if [ "$(git rev-list --count HEAD ^origin/main)" -eq 0 ]; then
            echo "No new commits to push."
            exit 0
          fi
          for a in 1 2 3; do
            echo "Push attempt $a..."
            if git push --force-with-lease; then exit 0; fi
            git rebase origin/main
            sleep 2
          done
          echo "Giving up after 3 attempts."; exit 1
